//
// Created by Dominik on 08.03.2023.
//

#ifndef COMPILATION_THEORY_AND_COMPILERS_AUTOMATA_H
#define COMPILATION_THEORY_AND_COMPILERS_AUTOMATA_H


class Automata {

};


#endif //COMPILATION_THEORY_AND_COMPILERS_AUTOMATA_H
